### ISSUE TITLE
Unused import in iotics/api/twin.proto

### ISSUE THREAD

**Issue by poggs** [Iotic-Labs/api#13]
When compiling the proto files, protoc reports `[WARNING] PROTOC: iotics/api/twin.proto:6:1: warning: Import google/protobuf/wrappers.proto is unused.`

It seems that wrappers. proto isn't used within twin.proto, and could be removed subject to review.

**Comment by conbon** [comment]
@StephanieBracaloni could maybe address this in latest PR?

**Comment by conbon** [comment]
Resolved in https://github.com/Iotic-Labs/api/pull/16. Thanks @poggs
